### ISSUE TITLE
Dockerfile Issue during environment setup 

### ISSUE THREAD

**Issue by Med16-11** [VallariAg/teuthology-api#16]
Hello mentors! @kamoltat @amathuria 
I was successful in setting up the environment before the new merge. But after the merge when I tried again it was showing error as follow-
![image](https://user-images.githubusercontent.com/78318301/226399077-7290a62b-73bf-4820-ba7c-378e5a13334f.png)

But when I removed  "COPY .env* /teuthology_api/ " from Teuthology API's dockerfile. I didn't encounter any error.  I am not sure how this is affecting environment, but I think removing it might helps in making installation easy. 
Do let me know if I am right or not. Thank you!

**Comment by kamoltat** [comment]
@Med16-11 should be good now, let me know if there are still problens
